"""create_conversation_turns

Revision ID: c1151f0a935d
Revises: 
Create Date: 2026-02-27 07:54:41.621225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1151f0a935d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique turn identifier (generated by the database).'),
    sa.Column('session_id', sa.String(length=128), nullable=False, comment='Groups turns belonging to the same conversation session.'),
    sa.Column('question', sa.Text(), nullable=False, comment='Raw user question as received by the agent.'),
    sa.Column('answer', sa.Text(), nullable=False, comment='Final answer string produced by llm_node.'),
    sa.Column('routing_decision', sa.String(length=32), nullable=False, comment="Router output: 'rag', 'direct', or 'out_of_scope'."),
    sa.Column('ragas_scores', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment="RAGAS evaluation metrics dict, e.g. {'faithfulness': 0.92, 'answer_relevance': 0.87}. NULL when the turn was not evaluated."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Wall-clock time when the turn was persisted (set by the DB server).'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_turns_session_created', 'conversation_turns', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_index('ix_conversation_turns_session_created', table_name='conversation_turns')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
