"""
SQLAlchemy async ORM model for persisting conversation turns.

Each row represents one complete question→answer exchange processed by the
LangGraph agent.  The table is append-only — rows are never updated after
insert, which simplifies audit logging and makes it safe for concurrent writes.

Why store both ``routing_decision`` and ``ragas_scores``?
---------------------------------------------------------
• ``routing_decision`` lets us analyse the distribution of query types over
  time (how many RAG vs direct vs refused requests) without replaying the
  full routing call.

• ``ragas_scores`` is nullable JSON so the column is always present but only
  populated when the EVALUATOR node ran (``evaluate=True`` on the request).
  Using JSON (not separate float columns) keeps the schema flexible as we add
  new RAGAS metrics without needing migrations.

Session / engine
----------------
This model uses the async declarative base from ``app.db.session`` so all
I/O can be awaited in FastAPI endpoint handlers and LangGraph nodes without
blocking the event loop.
"""

from __future__ import annotations

import uuid

from sqlalchemy import DateTime, Index, String, Text, func
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models in this project."""


class ConversationTurn(Base):
    """
    One question→answer turn processed by the RAG agent.

    Column layout
    -------------
    id               : UUID PK — uniquely identifies the turn; generated by the
                       DB server so application code never needs to create UUIDs.
    session_id       : Groups turns belonging to the same user session / chat
                       thread.  Indexed for efficient per-session history queries.
    question         : The raw user question as received by the agent.
    answer           : The final answer string written by ``llm_node``.
    routing_decision : One of ``'rag'``, ``'direct'``, ``'out_of_scope'``.
                       Stored to enable analytics on query-type distribution.
    ragas_scores     : Nullable JSON dict of RAGAS evaluation metrics, e.g.
                       ``{"faithfulness": 0.92, "answer_relevance": 0.87}``.
                       NULL when the request was not evaluated.
    created_at       : Server-side timestamp set at insert time; never updated.
    """

    __tablename__ = "conversation_turns"

    # ---------------------------------------------------------------------- #
    # Primary key                                                             #
    # ---------------------------------------------------------------------- #

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        # Let PostgreSQL generate the UUID so inserts need no round-trip to
        # fetch a new ID from the application layer.
        server_default=func.gen_random_uuid(),
        comment="Unique turn identifier (generated by the database).",
    )

    # ---------------------------------------------------------------------- #
    # Core turn data                                                          #
    # ---------------------------------------------------------------------- #

    session_id: Mapped[str] = mapped_column(
        String(128),
        nullable=False,
        index=True,   # B-tree index for fast session history lookups
        comment="Groups turns belonging to the same conversation session.",
    )

    question: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Raw user question as received by the agent.",
    )

    answer: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Final answer string produced by llm_node.",
    )

    # ---------------------------------------------------------------------- #
    # Routing metadata                                                        #
    # ---------------------------------------------------------------------- #

    routing_decision: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        comment="Router output: 'rag', 'direct', or 'out_of_scope'.",
    )

    # ---------------------------------------------------------------------- #
    # Evaluation scores (optional)                                            #
    # ---------------------------------------------------------------------- #

    ragas_scores: Mapped[dict | None] = mapped_column(
        # Use the PostgreSQL-native JSON type (not JSONB) — we only ever
        # store and retrieve these scores; we don't query inside the JSON.
        # If querying inside the JSON becomes necessary, migrate to JSONB.
        JSON,
        nullable=True,
        default=None,
        comment=(
            "RAGAS evaluation metrics dict, e.g. "
            "{'faithfulness': 0.92, 'answer_relevance': 0.87}. "
            "NULL when the turn was not evaluated."
        ),
    )

    # ---------------------------------------------------------------------- #
    # Timestamps                                                              #
    # ---------------------------------------------------------------------- #

    created_at: Mapped[DateTime] = mapped_column(
        # ``timezone=True`` stores timestamps as UTC in PostgreSQL (TIMESTAMPTZ).
        # Always use timezone-aware datetimes in a multi-region application.
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        comment="Wall-clock time when the turn was persisted (set by the DB server).",
    )

    # ---------------------------------------------------------------------- #
    # Composite index for common access pattern: session history ordered by  #
    # time.  The single-column index on session_id is still kept for filters #
    # that don't need ordering.                                               #
    # ---------------------------------------------------------------------- #

    __table_args__ = (
        Index(
            "ix_conversation_turns_session_created",
            "session_id",
            "created_at",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<ConversationTurn id={self.id!s:.8} "
            f"session={self.session_id!r} "
            f"route={self.routing_decision!r}>"
        )
